In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
(pd.__version__)

'2.2.3'

In [ ]:
# panads to Series
import pandas as pd
new=pd.Series([1,2,3,4,5])
new

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#pandas to series
import pandas as pd
marks=pd.Series([85,56,23,14,74])
print(marks)

0    85
1    56
2    23
3    14
4    74
dtype: int64

panads automattically assigns an index to every value

In [ ]:
import pandas as pd
num=[10,20,30,4,5]
print(pd.Series(num))

0    10
1    20
2    30
3     4
4     5
dtype: int64

In [ ]:
import pandas as pd
num=(10,20,30,4,5)
print(pd.Series(num))

0    10
1    20
2    30
3     4
4     5
dtype: int64

In [ ]:
#pandas to array
import pandas as pd

num=np.array([10,20,30,4,5])
print(pd.Series(num))

0    10
1    20
2    30
3     4
4     5
dtype: int64

In [ ]:
import pandas as pd
import numpy as np
num=np.array([10,20,30,4,5])
print(pd.Series(num))

0    10
1    20
2    30
3     4
4     5
dtype: int64

In [ ]:
import pandas as pd
num=[1,2,3,4,5,6,7,8]
print(num)
print(num[1])
print(num[2:5])

[1, 2, 3, 4, 5, 6, 7, 8]
2
[3, 4, 5]

In [ ]:
#pandas to dictionary
import pandas as pd
student={"name":"sangeeta",
         "reg_no":112,
         "place":"gadag",
         "college":"jt",
         "year":2026,
         "result":"pass"}
demo=pd.Series(student)
print(demo)
print(demo[1])
print(demo["college"])
print(demo[-2])

name       sangeeta
reg_no          112
place         gadag
college          jt
year           2026
result         pass
dtype: object
112
jt
2026

/tmp/ipykernel_2471/3592129125.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(demo[1])
/tmp/ipykernel_2471/3592129125.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(demo[-2])

In [ ]:
import pandas as pd
n=[12,3,4,5,2]
mul=pd.Series(n)
print(mul.dtype)
print(mul.size)
print(mul.shape)
print(mul.index)
print(mul.values)
print(mul*2)

In [ ]:
import pandas as pd
import numpy as np
arr=np.array([1,5,9,3,5,7])
arr+=5
arr
new=pd.Series(arr)
new
print(new*2)
print(new[new<=10])
new.shape
print(new.size)
print(new.index)
print(new.values)
print(new.dtype)

Data Frame

In [ ]:
import pandas as pd
demo={"reg_no":[112,111,193,41,568,156],
      "name":["sangeeta","veena","keerti", "sushila","akash","pawan"],
      "age":[19,23,45,12,56,20],
      "place":["gadag","narasapur","hubli","betageri","bagalkot","davangere"]}
demo

data=pd.DataFrame(demo)
data

   reg_no      name  age      place
0     112  sangeeta   19      gadag
1     111     veena   23  narasapur
2     193    keerti   45      hubli
3      41   sushila   12   betageri
4     568     akash   56   bagalkot
5     156     pawan   20  davangere

In [ ]:
# 2)csv file to dataframe
import pandas as pd
data=pd.read_csv("/content/Employees.csv")
data

In [ ]:
import pandas as pd
data=pd.read_excel("/content/Employees.xlsx")
data

   Emp_id      name  salary    company
0     101  sangeeta  100000        TCS
1     102     Bhuvi  300000  microsoft
2     103    sahana  400000      wipro
3     104     divya  800000     amazon
4     105   sanjana  560000   flipkart

In [ ]:
data["salary"]

In [ ]:
data["company"]

In [ ]:
import pandas as pd
data=pd.read_csv("Employees.csv")
data
data[["name","salary"]]

In [ ]:
data["Age"]=[12,32,65,48,25]
data.to_csv("Age",index=False)
data
data["Place"]=["Gadag","Bengaluru","Davangere","Mysore","Hyderabad"]
data

   Emp_id    company      Place  Age
0     101        TCS      Gadag   12
1     102  microsoft  Bengaluru   32
2     103      wipro  Davangere   65
3     104     amazon     Mysore   48
4     105   flipkart  Hyderabad   25

In [ ]:
data["Place"]=["Gadag","Bengaluru","Davangere","Mysore","Hyderabad"]
data

   Emp_id    company      Place
0     101        TCS      Gadag
1     102  microsoft  Bengaluru
2     103      wipro  Davangere
3     104     amazon     Mysore
4     105   flipkart  Hyderabad

In [ ]:
data["Place"]=["Gadag","Bengaluru","Davangere","Mysore","Hyderabad"]
data

   Emp_id      name  salary    company      Place
0     101  sangeeta  100000        TCS      Gadag
1     102     Bhuvi  300000  microsoft  Bengaluru
2     103    sahana  400000      wipro  Davangere
3     104     divya  800000     amazon     Mysore
4     105   sanjana  560000   flipkart  Hyderabad

In [ ]:
(data.columns)

Index(['Emp_id', 'name', 'salary', 'company', 'Place'], dtype='object')

In [ ]:
(data.index)

RangeIndex(start=0, stop=5, step=1)

In [ ]:
(data.dtypes)

Emp_id      int64
name       object
salary      int64
company    object
Place      object
dtype: object

In [ ]:
(data.shape)

(5, 5)

The Explorer's Toolkit

In [ ]:
data.head()

   Emp_id      name  salary    company      Place
0     101  sangeeta  100000        TCS      Gadag
1     102     Bhuvi  300000  microsoft  Bengaluru
2     103    sahana  400000      wipro  Davangere
3     104     divya  800000     amazon     Mysore
4     105   sanjana  560000   flipkart  Hyderabad

In [ ]:
data.tail()

   Emp_id      name  salary    company      Place
0     101  sangeeta  100000        TCS      Gadag
1     102     Bhuvi  300000  microsoft  Bengaluru
2     103    sahana  400000      wipro  Davangere
3     104     divya  800000     amazon     Mysore
4     105   sanjana  560000   flipkart  Hyderabad

In [ ]:
data.describe()

           Emp_id         salary
count    5.000000       5.000000
mean   103.000000  432000.000000
std      1.581139  264801.812683
min    101.000000  100000.000000
25%    102.000000  300000.000000
50%    103.000000  400000.000000
75%    104.000000  560000.000000
max    105.000000  800000.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Emp_id   5 non-null      int64
 1   name     5 non-null      object
 2   salary   5 non-null      int64
 3   company  5 non-null      object
 4   Place    5 non-null      object
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes

In [ ]:
import pandas as pd
employee={
    "ID":[101,102,103,104],
    "Name":["Rahul","Anita","John","Kiran"],
    "Department":["IT","HR","Sales","IT"],
    "Salary":[50000,45000,60000,55000]
}
df=pd.DataFrame(employee)
df

    ID   Name Department  Salary
0  101  Rahul         IT   50000
1  102  Anita         HR   45000
2  103   John      Sales   60000
3  104  Kiran         IT   55000

In [ ]:
print(df["Salary"].mean())

52500.0

Isolating the IT department

In [ ]:
(df[df["Department"]=="IT"])

    ID   Name Department  Salary
0  101  Rahul         IT   50000
3  104  Kiran         IT   55000

Cleaning
1)Missing value
2)Extra space
3)Outlayer value
4)Incomplte number
5)Outof frame no.

In [ ]:
import pandas as pd
data=pd.read_excel("/content/Employee_info.xlsx")
data

,Employee ID,Name,Age,Gender,Department,Salary,City,Joining Date
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,NaN,F,HR,38000,Chennai,2022-02-15
2,E103,John,28.0,Male,Finance,55000,NaN,2023-05-10
3,E104,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,NaN,Female,HR,-38000,Chennai,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,NaN,-27.0,Female,Finance,52000,Hyderabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,999999,Chennai,2024-01-05